name: CreateInstaller

on: [release]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run Inno Compiler
      run: iscc "installer\theonionpack.iss"
