name: Create Installer for The Onion Pack

on: [release]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run Inno Compiler
      run: iscc "installer\theonionpack.iss"

    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: TheOnionPackInstaller.exe application/vnd.microsoft.portable-executable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
